# Generated by Django 4.1.7 on 2023-04-13 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="meta_description",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="ディスクリプション"
            ),
        ),
    ]
