# Generated by Django 4.1.7 on 2023-02-28 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500, verbose_name="商品名")),
                ("price", models.IntegerField(verbose_name="価格")),
                ("caption", models.TextField(max_length=1000, verbose_name="商品紹介")),
                ("item_url", models.CharField(max_length=500, verbose_name="商品URL")),
                ("hash", models.CharField(max_length=500, verbose_name="ハッシュ値")),
                (
                    "image",
                    models.ImageField(upload_to="item_images/", verbose_name="商品画像"),
                ),
            ],
            options={
                "verbose_name": "商品",
                "verbose_name_plural": "商品",
                "db_table": "items",
            },
        ),
    ]
