# Generated by Django 4.1.7 on 2023-03-01 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_item_image_url"),
    ]

    operations = [
        migrations.RemoveField(model_name="item", name="hash",),
        migrations.AddField(
            model_name="item",
            name="item_code",
            field=models.CharField(default=1, max_length=500, verbose_name="アイテムコード"),
            preserve_default=False,
        ),
    ]
