# Generated by Django 4.1.7 on 2023-03-04 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_item_capacity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="capacity",
            field=models.IntegerField(default=0, verbose_name="容量"),
        ),
    ]
