# Generated by Django 4.1.7 on 2023-04-04 12:12

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_alter_item_capacity"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="seller",
            field=models.CharField(
                default="rakuten",
                max_length=100,
                validators=[main.models.validate_value],
                verbose_name="販売サイト",
            ),
            preserve_default=False,
        ),
    ]
