# Generated by Django 4.1.7 on 2023-04-15 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_alter_item_capacity_alter_item_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="rank",
            field=models.BigIntegerField(default=0, verbose_name="順位"),
        ),
    ]
